replicaCount: 2

image:
  repository: 329995585174.dkr.ecr.ap-south-1.amazonaws.com/devops-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20