apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-devops-app-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: devops-app

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
